<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pl5i8KhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pl5i8Kh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pl5i8Kh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ewishMailerService' => ['privates', 'App\\Easyjet\\EwishBundle\\Services\\EwishMailerService', 'getEwishMailerServiceService', true],
        ], [
            'ewishMailerService' => 'App\\Easyjet\\EwishBundle\\Services\\EwishMailerService',
        ]);
    }
}
