<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xfox44SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xfox44S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xfox44S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'log' => ['privates', 'App\\Easyjet\\FdtrBundle\\Entity\\FdtrLog', 'getFdtrLogService', true],
        ], [
            'log' => 'App\\Easyjet\\FdtrBundle\\Entity\\FdtrLog',
        ]);
    }
}
