<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LSZQ3WWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LSZQ3WW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LSZQ3WW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'xlsExporter' => ['privates', 'App\\Easyjet\\OtpBundle\\Services\\ExportOtpFileService', 'getExportOtpFileServiceService', true],
        ], [
            'xlsExporter' => 'App\\Easyjet\\OtpBundle\\Services\\ExportOtpFileService',
        ]);
    }
}
