<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0z0K0jwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0z0K0jw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0z0K0jw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'file' => ['privates', 'App\\Easyjet\\SfsuBundle\\Entity\\SfsuFile', 'getSfsuFileService', true],
        ], [
            'file' => 'App\\Easyjet\\SfsuBundle\\Entity\\SfsuFile',
        ]);
    }
}
