<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IYXCm40Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IYXCm40' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IYXCm40'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fixRequestAssignation' => ['privates', 'App\\Easyjet\\OtpBundle\\Services\\FixRequestAssignation', 'getFixRequestAssignationService', true],
        ], [
            'fixRequestAssignation' => 'App\\Easyjet\\OtpBundle\\Services\\FixRequestAssignation',
        ]);
    }
}
