<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gi0cw9EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gi0cw9E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gi0cw9E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demographicData' => ['privates', 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint096DemographicData', 'getHrisEjint096DemographicDataService', true],
        ], [
            'demographicData' => 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint096DemographicData',
        ]);
    }
}
