<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ly4W9dJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ly4W9dJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ly4W9dJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'monthlyReport' => ['privates', 'App\\Easyjet\\FdtrBundle\\Entity\\FdtrMonthlyReport', NULL, 'Cannot autowire service "App\\Easyjet\\FdtrBundle\\Entity\\FdtrMonthlyReport": argument "$month" of method "__construct()" references class "DateTIme" but no such service exists.'],
        ], [
            'monthlyReport' => 'App\\Easyjet\\FdtrBundle\\Entity\\FdtrMonthlyReport',
        ]);
    }
}
