<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Jn5sl2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..jn5sl2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..jn5sl2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'log' => ['privates', 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint096Log', 'getHrisEjint096LogService', true],
        ], [
            'log' => 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint096Log',
        ]);
    }
}
