<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SThS36Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sThS3_6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sThS3_6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sectorPay' => ['privates', 'App\\Easyjet\\OtpBundle\\Entity\\SectorPay', 'getSectorPayService', true],
        ], [
            'sectorPay' => 'App\\Easyjet\\OtpBundle\\Entity\\SectorPay',
        ]);
    }
}
