<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AA4n4p5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AA4n4p5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AA4n4p5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'log' => ['privates', 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint097Log', 'getHrisEjint097LogService', true],
        ], [
            'log' => 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint097Log',
        ]);
    }
}
