<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminDisruptionsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Easyjet\OtpBundle\Controller\AdminDisruptionsController' shared autowired service.
     *
     * @return \App\Easyjet\OtpBundle\Controller\AdminDisruptionsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'OtpBundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AdminDisruptionsController.php';

        $container->services['App\\Easyjet\\OtpBundle\\Controller\\AdminDisruptionsController'] = $instance = new \App\Easyjet\OtpBundle\Controller\AdminDisruptionsController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Easyjet\\OtpBundle\\Controller\\AdminDisruptionsController', $container));

        return $instance;
    }
}
