<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEjint096ImporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'ejint096_importer' shared service.
     *
     * @return \App\Easyjet\HrisBundle\Services\Ejint096ImporterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'HrisBundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'Ejint096ImporterService.php';

        return $container->services['ejint096_importer'] = new \App\Easyjet\HrisBundle\Services\Ejint096ImporterService('/data02/hris/ejint096/archives', '/data02/hris/tmp');
    }
}
