<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFestivalDateCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Easyjet\EwishBundle\Command\FestivalDateCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Easyjet\\EwishBundle\\Command\\FestivalDateCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:update-ewish-festival-period-date', [], 'Updates the EwishFestivalPeriodDate table with current year', false, function () use ($container): \App\Easyjet\EwishBundle\Command\FestivalDateCommand {
            return ($container->privates['App\\Easyjet\\EwishBundle\\Command\\FestivalDateCommand'] ?? $container->load('getFestivalDateCommandService'));
        });
    }
}
