<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFdtrImporterLogMailerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'fdtr_importer_log_mailer' shared autowired service.
     *
     * @return \App\Easyjet\FdtrBundle\Services\FdtrImporterMailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'FdtrBundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'FdtrImporterMailerService.php';

        return $container->services['fdtr_importer_log_mailer'] = new \App\Easyjet\FdtrBundle\Services\FdtrImporterMailerService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
