<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHrisUsersDisablerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hris_users_disabler' shared service.
     *
     * @return \App\Easyjet\HrisBundle\Services\UsersDisablerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'HrisBundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'UsersDisablerService.php';

        return $container->services['hris_users_disabler'] = new \App\Easyjet\HrisBundle\Services\UsersDisablerService($container->getEnv('ldap_root'), $container->getEnv('ldap_server'), $container->getEnv('ldap_bind'), $container->getEnv('ldap_ad_user'), $container->getEnv('ldap_ad_password'), $container->getEnv('ldap_find_by_emp_id'));
    }
}
