<?php

namespace ContainerA5p4xE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestMailerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\EleaveBundle\Services\RequestMailerService' shared autowired service.
     *
     * @return \App\Easyjet\EleaveBundle\Services\RequestMailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'EleaveBundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'RequestMailerService.php';

        return $container->privates['App\\Easyjet\\EleaveBundle\\Services\\RequestMailerService'] = new \App\Easyjet\EleaveBundle\Services\RequestMailerService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
