<?php

namespace App\Easyjet\FdtrBundle\Repository;

use Doctrine\ORM\EntityRepository;
use App\Easyjet\FdtrBundle\Entity\Users;
use App\Easyjet\FdtrBundle\Entity\FdtrMonthlyReport;
use App\Easyjet\FdtrBundle\Entity\FdtrExternalDtime;

/**
 * FdtrExternalDtimeBreakupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FdtrExternalDtimeBreakupRepository extends EntityRepository
{
}
