parameters:
    hris.grosstonet_file_folder: "/root/grosstonet_file_folder"
    hris.ejint096_archive_folder: /data02/hris/ejint096/archives
    hris.ejint097_archive_folder: /data02/hris/ejint097/archives
    hris.tmp_folder: /data02/hris/tmp
    hris.cosmic_radiation: /data02/hris/cosmic_radiation
    
    # hris.picofs_folder: smb://-hrisservice-swiss:akPypdoaf993@sgvahr0001/EDA_REP/unknown
    hris.picofs_folder: /mnt
    hris.picofs_extensions:
        - xml
        - xml.pgp
    
    ##dev 
    hris.workday.employeeRankingReport.url: "https://wd3-impl-services1.workday.com/ccx/service/customreport2/easyjet/IntCR_CH_user/EJ_-_Switzerland_Employee_Ranking_Report__Active_and_Term__-_WebService"
    #hris.workday.employeeRankingReport.url: "https://wd3-services1.myworkday.com/ccx/service/customreport2/easyjet/IntCR_CH_user/EJ_-_Switzerland_Employee_Ranking_Report__Active_and_Term__-_WebService"
    hris.workday.employeeRankingReport.login : "IntCR_CH_user"
    hris.workday.employeeRankingReport.password : "Workday$2"
    
    # Define below the list of emails address of the people intrested to receive the import report
    hris.users_import_email_addresses:
        - vikant.tyagi@easyjet.com
        - vincent.libsig@easyjet.com
    hris.ejint097_transfer_notification:
        - servicecentre@safeguardworld.com
        - vincent.libsig@easyjet.com
    hris.mover_alert_to_itsd:
        - easyjetitservicedesk@easyjet.com
        - vikrant.tyagi@easyjet.com
        - vincent.libsig@easyjet.com
        - anthony.garrelhas2@easyjet.com
        - ezs-itdeskengineer@easyjet.com
    
services:
    ejint097_analyser:
        class: Easyjet\HrisBundle\Services\Ejint097AnalyserService
        arguments: ["@mailer", "%hris.grosstonet_file_folder%", "%hris.ejint097_archive_folder%", "%hris.tmp_folder%"]
    ejint097_importer:
        class: App\Easyjet\HrisBundle\Services\Ejint097ImporterService
        arguments: ["@mailer", "%hris.grosstonet_file_folder%", "%hris.ejint097_archive_folder%", "%hris.tmp_folder%"]
        public: true
    ejint097b_importer:
        class: App\Easyjet\HrisBundle\Services\Ejint097bImporterService
        arguments: ["@mailer", "%hris.grosstonet_file_folder%", "%hris.ejint097_archive_folder%", "%hris.tmp_folder%"]
        public: true
    ejint096_importer:
        class: App\Easyjet\HrisBundle\Services\Ejint096ImporterService
        arguments: ["%hris.ejint096_archive_folder%", "%hris.tmp_folder%"]
        public: true
    ejint096_tester:
        class: App\Easyjet\HrisBundle\Services\Ejint096TesterService
        arguments: ["%hris.ejint096_archive_folder%/data-check"]
        public: true
    hris_users_importer:
        class: App\Easyjet\HrisBundle\Services\UsersImporterService
        arguments: []
        public: true
    hris_users_disabler:
        class: App\Easyjet\HrisBundle\Services\UsersDisablerService
        arguments: ['%ldap_root%', '%ldap_server%', '%ldap_bind%', '%ldap_ad_user%', '%ldap_ad_password%', '%ldap_find_by_emp_id%']
        public: true
    hris_mailer:
        class: App\Easyjet\HrisBundle\Services\HrisMailerService
        arguments: ['@mailer']
        public: true
      
