<?php

namespace Proxies\__CG__\App\Easyjet\OtpBundle\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OtpImportRow extends \App\Easyjet\OtpBundle\Entity\OtpImportRow implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'id', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'batch', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'empno', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'hireDate', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'compensationGrade', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'typeEftr', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'firstname', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'lastname', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectN', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectS', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectM', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectL', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectXL', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectManualTaxedChf', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectManualNotTaxedChf', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'disruptionComment', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'disruptions', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectorsAdjustments', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'exportedIn', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'exportedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'id', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'batch', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'empno', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'hireDate', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'compensationGrade', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'typeEftr', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'firstname', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'lastname', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectN', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectS', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectM', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectL', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectXL', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectManualTaxedChf', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectManualNotTaxedChf', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'disruptionComment', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'disruptions', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'sectorsAdjustments', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'exportedIn', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow' . "\0" . 'exportedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OtpImportRow $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addDisruption(\App\Easyjet\OtpBundle\Entity\OtpDisruption $disruption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDisruption', [$disruption]);

        return parent::addDisruption($disruption);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisruptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisruptions', []);

        return parent::getDisruptions();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getBatch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBatch', []);

        return parent::getBatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setBatch(\App\Easyjet\OtpBundle\Entity\OtpImportBatch $batch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBatch', [$batch]);

        return parent::setBatch($batch);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpno', []);

        return parent::getEmpno();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpno($empno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpno', [$empno]);

        return parent::setEmpno($empno);
    }

    /**
     * {@inheritDoc}
     */
    public function getHireDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHireDate', []);

        return parent::getHireDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setHireDate(\DateTime $hireDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHireDate', [$hireDate]);

        return parent::setHireDate($hireDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompensationGrade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompensationGrade', []);

        return parent::getCompensationGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompensationGrade($compensationGrade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompensationGrade', [$compensationGrade]);

        return parent::setCompensationGrade($compensationGrade);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeEftr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeEftr', []);

        return parent::getTypeEftr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeEftr(\App\Easyjet\UmanBundle\Entity\TypesEftr $typeEftr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeEftr', [$typeEftr]);

        return parent::setTypeEftr($typeEftr);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectN()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectN', []);

        return parent::getSectN();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectN($sectN)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectN', [$sectN]);

        return parent::setSectN($sectN);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectS()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectS', []);

        return parent::getSectS();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectS($sectS)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectS', [$sectS]);

        return parent::setSectS($sectS);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectM()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectM', []);

        return parent::getSectM();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectM($sectM)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectM', [$sectM]);

        return parent::setSectM($sectM);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectXL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectXL', []);

        return parent::getSectXL();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectXL($sectXL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectXL', [$sectXL]);

        return parent::setSectXL($sectXL);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectL', []);

        return parent::getSectL();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectL($sectL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectL', [$sectL]);

        return parent::setSectL($sectL);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectManualTaxedChf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectManualTaxedChf', []);

        return parent::getSectManualTaxedChf();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectManualTaxedChf($sectManualTaxedChf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectManualTaxedChf', [$sectManualTaxedChf]);

        return parent::setSectManualTaxedChf($sectManualTaxedChf);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectManualNotTaxedChf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectManualNotTaxedChf', []);

        return parent::getSectManualNotTaxedChf();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectManualNotTaxedChf($sectManualNotTaxedChf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectManualNotTaxedChf', [$sectManualNotTaxedChf]);

        return parent::setSectManualNotTaxedChf($sectManualNotTaxedChf);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisruptionComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisruptionComment', []);

        return parent::getDisruptionComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisruptionComment($disruptionComment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisruptionComment', [$disruptionComment]);

        return parent::setDisruptionComment($disruptionComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getExportedIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportedIn', []);

        return parent::getExportedIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setExportedIn(\App\Easyjet\OtpBundle\Entity\ExportLog $exportedIn = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportedIn', [$exportedIn]);

        return parent::setExportedIn($exportedIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getExportedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportedAt', []);

        return parent::getExportedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setExportedAt(\DateTime $exportedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportedAt', [$exportedAt]);

        return parent::setExportedAt($exportedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSectorsAdjustments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSectorsAdjustments', []);

        return parent::getSectorsAdjustments();
    }

    /**
     * {@inheritDoc}
     */
    public function setSectorsAdjustments($sectorsAdjustments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSectorsAdjustments', [$sectorsAdjustments]);

        return parent::setSectorsAdjustments($sectorsAdjustments);
    }

    /**
     * {@inheritDoc}
     */
    public function addSectorsAdjustments($adjustment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSectorsAdjustments', [$adjustment]);

        return parent::addSectorsAdjustments($adjustment);
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        return parent::preUpdate();
    }

}
