<?php

namespace Proxies\__CG__\App\Easyjet\OtpBundle\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OtpDisruption extends \App\Easyjet\OtpBundle\Entity\OtpDisruption implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'id', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'row', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'request', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'state', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'exportedIn', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'exportedAt', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'date', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'statusChangedAt', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'initialStart', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'initialEnd', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'newStart', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'newEnd', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'dateOfChange', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'refuseReason', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'initialState'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'id', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'row', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'request', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'state', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'exportedIn', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'exportedAt', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'date', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'statusChangedAt', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'initialStart', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'initialEnd', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'newStart', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'newEnd', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'dateOfChange', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'refuseReason', '' . "\0" . 'App\\Easyjet\\OtpBundle\\Entity\\OtpDisruption' . "\0" . 'initialState'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OtpDisruption $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function postLoad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'postLoad', []);

        return parent::postLoad();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getRequest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequest', []);

        return parent::getRequest();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequest(\App\Easyjet\OtpBundle\Entity\OtpRequest $request)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequest', [$request]);

        return parent::setRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusChangedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusChangedAt', []);

        return parent::getStatusChangedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusChangedAt(\DateTime $statusChangedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusChangedAt', [$statusChangedAt]);

        return parent::setStatusChangedAt($statusChangedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getRow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRow', []);

        return parent::getRow();
    }

    /**
     * {@inheritDoc}
     */
    public function setRow(\App\Easyjet\OtpBundle\Entity\OtpImportRow $row)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRow', [$row]);

        return parent::setRow($row);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function setExportedIn(\App\Easyjet\OtpBundle\Entity\ExportLog $exportedIn = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportedIn', [$exportedIn]);

        return parent::setExportedIn($exportedIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getExportedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportedAt', []);

        return parent::getExportedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setExportedAt(\DateTime $exportedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportedAt', [$exportedAt]);

        return parent::setExportedAt($exportedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitialStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitialStart', []);

        return parent::getInitialStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialStart($initialStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialStart', [$initialStart]);

        return parent::setInitialStart($initialStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitialEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitialEnd', []);

        return parent::getInitialEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialEnd(\DateTime $initialEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialEnd', [$initialEnd]);

        return parent::setInitialEnd($initialEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewStart', []);

        return parent::getNewStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewStart(\DateTime $newStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewStart', [$newStart]);

        return parent::setNewStart($newStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewEnd', []);

        return parent::getNewEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewEnd(\DateTime $newEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewEnd', [$newEnd]);

        return parent::setNewEnd($newEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfChange()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfChange', []);

        return parent::getDateOfChange();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfChange(\DateTime $dateOfChange)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfChange', [$dateOfChange]);

        return parent::setDateOfChange($dateOfChange);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefuseReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefuseReason', []);

        return parent::getRefuseReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefuseReason($refuseReason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefuseReason', [$refuseReason]);

        return parent::setRefuseReason($refuseReason);
    }

}
