# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

parameters:
    fdtr.incoming_folder: /data02/fdtr/test
    fdtr.archive_folder: /data02/fdtr/archives
    fdtr.external_dtime_folder: /data02/fdtr/external_dtime
    fdtr.swissinside_url: https://swissinside.easyjet.com
    
 
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
   
    fdtr_importer:
        class: App\Easyjet\FdtrBundle\Services\FdtrImporterService
        public: true  
      
    fdtr_importer_log_mailer:
        class: App\Easyjet\FdtrBundle\Services\FdtrImporterMailerService
        arguments: ["@mailer", "@doctrine.orm.entity_manager"]
        public: true

    fdtr_reminder_log_mailer:
        class: App\Easyjet\FdtrBundle\Services\FdtrReminderMailerService
        arguments: ["@mailer", "@doctrine.orm.entity_manager"]
        public: true

    fdtr_user_block_mailer:
        class: App\Easyjet\FdtrBundle\Services\FdtrDtimeUserBlockMailerService
        arguments: ["@mailer", "@doctrine.orm.entity_manager"] 
        public: true  