# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    database_name: uman
    database_user: swissinside
    database_password: 46O540kyYS6v
  
    easyjet_env: swissinside
    oracle.host: '%env(ORACLE_HOST)%'
    oracle.login: '%env(ORACLE_LOGIN)%'
    oracle.password: '%env(ORACLE_PASSWORD)%'
    oracle.enable_connection: '%env(ORACLE_ENABLE_CONNECTION)%'
    oracle.instance: '%env(ORACLE_INSTANCE)%' 
    ldap_server: '%env(ldap_server)%'
    ldap_bind: '%env(ldap_bind)%'
    ldap_find_by_emp_id: '%env(ldap_find_by_emp_id)%'
    ldap_root: '%env(ldap_root)%'
    ldap_ad_user: '%env(ldap_ad_user)%'
    ldap_ad_password: '%env(ldap_ad_password)%'
    
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    
    security.authentication.switchuser_listener:
        class: App\Easyjet\SwissinsideCoreBundle\Listener\MySwitchUserListener
        arguments:
            - "@security.token_storage"
            - "@app.webservice_user_provider"
            - "@security.user_checker"
            - 'main'
            - "@security.access.decision_manager"
            - "@?monolog.logger.security"
            - '_impersonate'
            - 'ROLE_ALLOWED_TO_SWITCH'
            - "@?debug.event_dispatcher"
            - ['email1@domain.tld', 'email2@domain.tld']
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: monolog.logger, channel: security }
   

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Easyjet\SwissinsideCoreBundle\Security\LdapFormAuthenticator:
        arguments:
            $ldapServerAddress: '%env(ldap_server)%'
            $ldapBind: '%env(ldap_bind)%'
            $ldapFind: '%env(ldap_find)%'
            $ldapRoot:  '%env(ldap_root)%'
            $ldapAdminUsername: '%env(ldap_ad_user)%'
            $ldapAdminPassword: '%env(ldap_ad_password)%'
            $ldapFindByEmployeeId: '%env(ldap_find_by_emp_id)%'
            $ldapAdRights:  '%env(ldap_ad_rights)%'
            $allowUserToSwitchUser: '%env(allow_switch_user)%'
            $ldapManageableGroupsFilter: '%env(ldap_manageable_groups)%'
            $ldapAdManagerGroup:  '%env(ldap_ad_managers)%'
            $antiBruteForceMaxNbAttempts: '%env(anti_brute_force_max_nb_attempts)%'
            $antiBruteForceLockTime:  '%env(anti_brute_force_lock_time)%'
