<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kp4fN3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kp4fN_3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kp4fN_3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestMailerService' => ['privates', 'App\\Easyjet\\EleaveBundle\\Services\\RequestMailerService', 'getRequestMailerServiceService', true],
        ], [
            'requestMailerService' => 'App\\Easyjet\\EleaveBundle\\Services\\RequestMailerService',
        ]);
    }
}
