<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mp2qzfdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mp2qzfd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mp2qzfd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sectAdj' => ['privates', 'App\\Easyjet\\OtpBundle\\Entity\\OtpSectAdjClaimsRequest', 'getOtpSectAdjClaimsRequestService', true],
        ], [
            'sectAdj' => 'App\\Easyjet\\OtpBundle\\Entity\\OtpSectAdjClaimsRequest',
        ]);
    }
}
