<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PZF3gYpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pZF3gYp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pZF3gYp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bus' => ['privates', 'App\\Easyjet\\WorkingSheetBundle\\Services\\BulkUpdateService', 'getBulkUpdateServiceService', true],
        ], [
            'bus' => 'App\\Easyjet\\WorkingSheetBundle\\Services\\BulkUpdateService',
        ]);
    }
}
