<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WxoiCeJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WxoiCeJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WxoiCeJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendar' => ['privates', 'App\\Easyjet\\HrisBundle\\Entity\\HrisProcessingCalendar', 'getHrisProcessingCalendarService', true],
        ], [
            'calendar' => 'App\\Easyjet\\HrisBundle\\Entity\\HrisProcessingCalendar',
        ]);
    }
}
