<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6V39pFzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6V39pFz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6V39pFz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'payElement' => ['privates', 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint096PayElement', 'getHrisEjint096PayElementService', true],
        ], [
            'payElement' => 'App\\Easyjet\\HrisBundle\\Entity\\HrisEjint096PayElement',
        ]);
    }
}
