<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VllvBj2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vllvBj2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vllvBj2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'log' => ['privates', 'App\\Easyjet\\HrisBundle\\Entity\\HrisUsersImportLog', 'getHrisUsersImportLogService', true],
        ], [
            'log' => 'App\\Easyjet\\HrisBundle\\Entity\\HrisUsersImportLog',
        ]);
    }
}
