<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFeg1ZhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gFeg1Zh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gFeg1Zh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'row' => ['privates', 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow', 'getOtpImportRowService', true],
        ], [
            'row' => 'App\\Easyjet\\OtpBundle\\Entity\\OtpImportRow',
        ]);
    }
}
