<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBulkUpdateServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\WorkingSheetBundle\Services\BulkUpdateService' shared autowired service.
     *
     * @return \App\Easyjet\WorkingSheetBundle\Services\BulkUpdateService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'WorkingSheetBundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'BulkUpdateService.php';

        return $container->privates['App\\Easyjet\\WorkingSheetBundle\\Services\\BulkUpdateService'] = new \App\Easyjet\WorkingSheetBundle\Services\BulkUpdateService(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
