<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportLogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\OtpBundle\Entity\ExportLog' shared autowired service.
     *
     * @return \App\Easyjet\OtpBundle\Entity\ExportLog
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'OtpBundle'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'ExportLog.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'UmanBundle'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Users.php';

        return $container->privates['App\\Easyjet\\OtpBundle\\Entity\\ExportLog'] = new \App\Easyjet\OtpBundle\Entity\ExportLog(($container->privates['App\\Easyjet\\UmanBundle\\Entity\\Users'] ?? ($container->privates['App\\Easyjet\\UmanBundle\\Entity\\Users'] = new \App\Easyjet\UmanBundle\Entity\Users())), ($container->privates['App\\Easyjet\\OtpBundle\\Entity\\OtpImportBatch'] ?? $container->load('getOtpImportBatchService')));
    }
}
