<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Easyjet\\EleaveBundle\\Form\\EmailForm' => ['privates', 'App\\Easyjet\\EleaveBundle\\Form\\EmailForm', 'getEmailFormService', true],
            'App\\Easyjet\\EleaveBundle\\Form\\RefusForm' => ['privates', 'App\\Easyjet\\EleaveBundle\\Form\\RefusForm', 'getRefusFormService', true],
            'App\\Easyjet\\EleaveBundle\\Form\\RulesForm' => ['privates', 'App\\Easyjet\\EleaveBundle\\Form\\RulesForm', 'getRulesFormService', true],
            'App\\Easyjet\\EwishBundle\\Form\\EmailNotificationsForm' => ['privates', 'App\\Easyjet\\EwishBundle\\Form\\EmailNotificationsForm', 'getEmailNotificationsFormService', true],
            'App\\Easyjet\\FdtrBundle\\Form\\ExternalDutyForm' => ['privates', 'App\\Easyjet\\FdtrBundle\\Form\\ExternalDutyForm', 'getExternalDutyFormService', true],
            'App\\Easyjet\\FdtrBundle\\Form\\NotificationsForm' => ['privates', 'App\\Easyjet\\FdtrBundle\\Form\\NotificationsForm', 'getNotificationsFormService', true],
            'App\\Easyjet\\HrisBundle\\Form\\CosmicRadiationReportForm' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\CosmicRadiationReportForm', 'getCosmicRadiationReportFormService', true],
            'App\\Easyjet\\HrisBundle\\Form\\CrewUserReportForm' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\CrewUserReportForm', 'getCrewUserReportFormService', true],
            'App\\Easyjet\\HrisBundle\\Form\\DemographicDataForm' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\DemographicDataForm', 'getDemographicDataFormService', true],
            'App\\Easyjet\\HrisBundle\\Form\\DemographicDataSoftRuleType' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\DemographicDataSoftRuleType', 'getDemographicDataSoftRuleTypeService', true],
            'App\\Easyjet\\HrisBundle\\Form\\PayElementForm' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\PayElementForm', 'getPayElementFormService', true],
            'App\\Easyjet\\HrisBundle\\Form\\PayElementSoftRuleType' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\PayElementSoftRuleType', 'getPayElementSoftRuleTypeService', true],
            'App\\Easyjet\\HrisBundle\\Form\\ProcessingCalendarForm' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\ProcessingCalendarForm', 'getProcessingCalendarFormService', true],
            'App\\Easyjet\\HrisBundle\\Form\\UploadUserImportForm' => ['privates', 'App\\Easyjet\\HrisBundle\\Form\\UploadUserImportForm', 'getUploadUserImportFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\CompensationGradesForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\CompensationGradesForm', 'getCompensationGradesFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\DisruptionsForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\DisruptionsForm', 'getDisruptionsFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\ExportOtpFileForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\ExportOtpFileForm', 'getExportOtpFileFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\FactorisationsForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\FactorisationsForm', 'getFactorisationsFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\ImportFileForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\ImportFileForm', 'getImportFileFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\OtpImportCommentForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\OtpImportCommentForm', 'getOtpImportCommentFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\OtpImportRowCommentForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\OtpImportRowCommentForm', 'getOtpImportRowCommentFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\OtpImportRowForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\OtpImportRowForm', 'getOtpImportRowFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\OtpNewDisruptionAdjForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\OtpNewDisruptionAdjForm', 'getOtpNewDisruptionAdjFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\OtpNewSectAdjForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\OtpNewSectAdjForm', 'getOtpNewSectAdjFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\OtpSectAdjEditForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\OtpSectAdjEditForm', 'getOtpSectAdjEditFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\OtpSectAdjNewForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\OtpSectAdjNewForm', 'getOtpSectAdjNewFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\RequestsSearchForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\RequestsSearchForm', 'getRequestsSearchFormService', true],
            'App\\Easyjet\\OtpBundle\\Form\\SectorPayForm' => ['privates', 'App\\Easyjet\\OtpBundle\\Form\\SectorPayForm', 'getSectorPayFormService', true],
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuDownloadTokenForm' => ['privates', 'App\\Easyjet\\SfsuBundle\\Form\\SfsuDownloadTokenForm', 'getSfsuDownloadTokenFormService', true],
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileForm' => ['privates', 'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileForm', 'getSfsuFileFormService', true],
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileMailForm' => ['privates', 'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileMailForm', 'getSfsuFileMailFormService', true],
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileUploadForm' => ['privates', 'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileUploadForm', 'getSfsuFileUploadFormService', true],
            'App\\Easyjet\\SfsuBundle\\Form\\maxFileSizeUploadForm' => ['privates', 'App\\Easyjet\\SfsuBundle\\Form\\maxFileSizeUploadForm', 'getMaxFileSizeUploadFormService', true],
            'App\\Easyjet\\UmanBundle\\Form\\ApplicationsEditForm' => ['privates', 'App\\Easyjet\\UmanBundle\\Form\\ApplicationsEditForm', 'getApplicationsEditFormService', true],
            'App\\Easyjet\\UmanBundle\\Form\\ApplicationsForm' => ['privates', 'App\\Easyjet\\UmanBundle\\Form\\ApplicationsForm', 'getApplicationsFormService', true],
            'App\\Easyjet\\UmanBundle\\Form\\EmployeeUserForm' => ['privates', 'App\\Easyjet\\UmanBundle\\Form\\EmployeeUserForm', 'getEmployeeUserFormService', true],
            'App\\Easyjet\\UmanBundle\\Form\\ExternalUserForm' => ['privates', 'App\\Easyjet\\UmanBundle\\Form\\ExternalUserForm', 'getExternalUserFormService', true],
            'App\\Easyjet\\UmanBundle\\Form\\StationsForm' => ['privates', 'App\\Easyjet\\UmanBundle\\Form\\StationsForm', 'getStationsFormService', true],
            'App\\Easyjet\\UmanBundle\\Form\\ThirdPartyUserForm' => ['privates', 'App\\Easyjet\\UmanBundle\\Form\\ThirdPartyUserForm', 'getThirdPartyUserFormService', true],
            'App\\Easyjet\\UmanBundle\\Form\\TypesUsersForm' => ['privates', 'App\\Easyjet\\UmanBundle\\Form\\TypesUsersForm', 'getTypesUsersFormService', true],
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetActualWorkType' => ['privates', 'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetActualWorkType', 'getWorkingSheetActualWorkTypeService', true],
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetPatternType' => ['privates', 'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetPatternType', 'getWorkingSheetPatternTypeService', true],
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetPatternValidateType' => ['privates', 'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetPatternValidateType', 'getWorkingSheetPatternValidateTypeService', true],
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetSearchReportType' => ['privates', 'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetSearchReportType', 'getWorkingSheetSearchReportTypeService', true],
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetUsersType' => ['privates', 'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetUsersType', 'getWorkingSheetUsersTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', '.container.private.form.type.file', 'get_Container_Private_Form_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Easyjet\\EleaveBundle\\Form\\EmailForm' => '?',
            'App\\Easyjet\\EleaveBundle\\Form\\RefusForm' => '?',
            'App\\Easyjet\\EleaveBundle\\Form\\RulesForm' => '?',
            'App\\Easyjet\\EwishBundle\\Form\\EmailNotificationsForm' => '?',
            'App\\Easyjet\\FdtrBundle\\Form\\ExternalDutyForm' => '?',
            'App\\Easyjet\\FdtrBundle\\Form\\NotificationsForm' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\CosmicRadiationReportForm' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\CrewUserReportForm' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\DemographicDataForm' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\DemographicDataSoftRuleType' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\PayElementForm' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\PayElementSoftRuleType' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\ProcessingCalendarForm' => '?',
            'App\\Easyjet\\HrisBundle\\Form\\UploadUserImportForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\CompensationGradesForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\DisruptionsForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\ExportOtpFileForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\FactorisationsForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\ImportFileForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\OtpImportCommentForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\OtpImportRowCommentForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\OtpImportRowForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\OtpNewDisruptionAdjForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\OtpNewSectAdjForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\OtpSectAdjEditForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\OtpSectAdjNewForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\RequestsSearchForm' => '?',
            'App\\Easyjet\\OtpBundle\\Form\\SectorPayForm' => '?',
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuDownloadTokenForm' => '?',
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileForm' => '?',
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileMailForm' => '?',
            'App\\Easyjet\\SfsuBundle\\Form\\SfsuFileUploadForm' => '?',
            'App\\Easyjet\\SfsuBundle\\Form\\maxFileSizeUploadForm' => '?',
            'App\\Easyjet\\UmanBundle\\Form\\ApplicationsEditForm' => '?',
            'App\\Easyjet\\UmanBundle\\Form\\ApplicationsForm' => '?',
            'App\\Easyjet\\UmanBundle\\Form\\EmployeeUserForm' => '?',
            'App\\Easyjet\\UmanBundle\\Form\\ExternalUserForm' => '?',
            'App\\Easyjet\\UmanBundle\\Form\\StationsForm' => '?',
            'App\\Easyjet\\UmanBundle\\Form\\ThirdPartyUserForm' => '?',
            'App\\Easyjet\\UmanBundle\\Form\\TypesUsersForm' => '?',
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetActualWorkType' => '?',
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetPatternType' => '?',
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetPatternValidateType' => '?',
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetSearchReportType' => '?',
            'App\\Easyjet\\WorkingSheetBundle\\Form\\WorkingSheetUsersType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? $container->getDataCollector_FormService())));
    }
}
