<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFdtrLogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\FdtrBundle\Entity\FdtrLog' shared autowired service.
     *
     * @return \App\Easyjet\FdtrBundle\Entity\FdtrLog
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'FdtrBundle'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'FdtrLog.php';

        return $container->privates['App\\Easyjet\\FdtrBundle\\Entity\\FdtrLog'] = new \App\Easyjet\FdtrBundle\Entity\FdtrLog();
    }
}
