<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHrisProcessingCalendarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\HrisBundle\Entity\HrisProcessingCalendar' shared autowired service.
     *
     * @return \App\Easyjet\HrisBundle\Entity\HrisProcessingCalendar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'HrisBundle'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'HrisProcessingCalendar.php';

        return $container->privates['App\\Easyjet\\HrisBundle\\Entity\\HrisProcessingCalendar'] = new \App\Easyjet\HrisBundle\Entity\HrisProcessingCalendar();
    }
}
