<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOtpMailerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'otp_mailer' shared autowired service.
     *
     * @return \App\Easyjet\OtpBundle\Services\OtpMailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'OtpBundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'OtpMailerService.php';

        return $container->services['otp_mailer'] = new \App\Easyjet\OtpBundle\Services\OtpMailerService(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
