<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemainingDaysParserServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\EleaveBundle\Services\RemainingDaysParserService' shared autowired service.
     *
     * @return \App\Easyjet\EleaveBundle\Services\RemainingDaysParserService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'EleaveBundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'RemainingDaysParserService.php';

        return $container->privates['App\\Easyjet\\EleaveBundle\\Services\\RemainingDaysParserService'] = new \App\Easyjet\EleaveBundle\Services\RemainingDaysParserService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
