<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSfsuDownloadTokenFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\SfsuBundle\Form\SfsuDownloadTokenForm' shared autowired service.
     *
     * @return \App\Easyjet\SfsuBundle\Form\SfsuDownloadTokenForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'SfsuBundle'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'SfsuDownloadTokenForm.php';

        return $container->privates['App\\Easyjet\\SfsuBundle\\Form\\SfsuDownloadTokenForm'] = new \App\Easyjet\SfsuBundle\Form\SfsuDownloadTokenForm();
    }
}
