<?php

namespace ContainerWg7jGRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Easyjet\UmanBundle\Entity\Users' shared autowired service.
     *
     * @return \App\Easyjet\UmanBundle\Entity\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Easyjet'.\DIRECTORY_SEPARATOR.'UmanBundle'.\DIRECTORY_SEPARATOR.'Entity'.\DIRECTORY_SEPARATOR.'Users.php';

        return $container->privates['App\\Easyjet\\UmanBundle\\Entity\\Users'] = new \App\Easyjet\UmanBundle\Entity\Users();
    }
}
