<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5p4xE9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5p4xE9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA5p4xE9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA5p4xE9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA5p4xE9\App_KernelDevDebugContainer([
    'container.build_hash' => 'A5p4xE9',
    'container.build_id' => 'faf5b838',
    'container.build_time' => 1683558814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5p4xE9');
